[package]
name = "kool-craft-launcher"
version = "0.0.0"
description = ""
authors = ["MC_XiaoHei"]
edition = "2024"

[lib]
name = "kool_craft_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.9", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

window-vibrancy = "0.7.1"
os_info = "3.7"
wallpaper = "3.2"
log = "0.4"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
base64 = "0.22"
dirs = "6.0"
anyhow = "1.0"
tap = "1.0"
tauri-plugin-log = "2.7"
